### ISSUE TITLE
`scale_name` argument of `discrete_scale()` is deprecated in ggplot2

### ISSUE THREAD

**Issue by ustervbo** [tesselle/khroma#15]
**Describe the bug**

The `scale_name` argument of `discrete_scale()` is deprecated as of ggplot2 3.5.0.

**To Reproduce**

library(ggplot2)
options("lifecycle_verbosity"="warning")

plot_df <- data.frame(
  fill_col = c("A", "A", "B", "B"),
  pattern_col = c("a", "b", "a", "b"),
  value = c(1, 2, 3, 4)
)

options(
  list(
    ggplot2.discrete.fill = function() {
      khroma::scale_fill_picker(palette = "light")
    }
  ))

ggplot(plot_df) +
  aes(x = fill_col, y = value, fill = pattern_col) +
  geom_col(position = "dodge")

**Expected behavior**

No warning is raised.

**Comment by nfrerebeau** [comment]
Thanks for pointing that out!
